#ifndef __PRIORITY_H__
#define __PRIORITY_H__

#define PRIORITY_ROOT_TASK         500
#define PRIORITY_IDLE_TASK           1

#define PRIORITY_SERVER_CLOCK     3500
#define PRIORITY_SERVER_IO        3500
#define PRIORITY_SERVER_NAME      4000

#define PRIORITY_SERVER_RPS       2000
#define PRIORITY_SERVER_SHELL     2000
#define PRIORITY_SERVER_TMR       3000

#define PRIORITY_NOTIFIER_CLOCK   2500
#define PRIORITY_NOTIFIER_IO_COM1 2500
#define PRIORITY_NOTIFIER_IO_COM2 2500

#endif /* __PRIORITY_H__ */
